// <auto-generated />
namespace ISData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ISDB3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ISDB3));
        
        string IMigrationMetadata.Id
        {
            get { return "202206201128546_ISDB3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
